/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PORTA15 (number 45), LED_RED_RR
  @{ */
#define LED_LED_RED_RR_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define LED_LED_RED_RR_PORT PORTA /*!<@brief PORT device name: PORTA */
#define LED_LED_RED_RR_PIN 15U    /*!<@brief PORTA pin index: 15 */
                                  /* @} */

/*! @name PORTA17 (number 47), LED_RED_RL
  @{ */
#define LED_LED_RED_RL_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define LED_LED_RED_RL_PORT PORTA /*!<@brief PORT device name: PORTA */
#define LED_LED_RED_RL_PIN 17U    /*!<@brief PORTA pin index: 17 */
                                  /* @} */

/*! @name PORTC8 (number 80), LED_GREEN_FL
  @{ */
#define LED_LED_GREEN_FL_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define LED_LED_GREEN_FL_PORT PORTC /*!<@brief PORT device name: PORTC */
#define LED_LED_GREEN_FL_PIN 8U     /*!<@brief PORTC pin index: 8 */
                                    /* @} */

/*! @name PORTC9 (number 81), LED_RED_FL
  @{ */
#define LED_LED_RED_FL_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define LED_LED_RED_FL_PORT PORTC /*!<@brief PORT device name: PORTC */
#define LED_LED_RED_FL_PIN 9U     /*!<@brief PORTC pin index: 9 */
                                  /* @} */

/*! @name PORTC10 (number 82), LED_BLUE_FL
  @{ */
#define LED_LED_BLUE_FL_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define LED_LED_BLUE_FL_PORT PORTC /*!<@brief PORT device name: PORTC */
#define LED_LED_BLUE_FL_PIN 10U    /*!<@brief PORTC pin index: 10 */
                                   /* @} */

/*! @name PORTC11 (number 83), LED_GREEN_FR
  @{ */
#define LED_LED_GREEN_FR_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define LED_LED_GREEN_FR_PORT PORTC /*!<@brief PORT device name: PORTC */
#define LED_LED_GREEN_FR_PIN 11U    /*!<@brief PORTC pin index: 11 */
                                    /* @} */

/*! @name PORTD2 (number 95), LED_RED_FR
  @{ */
#define LED_LED_RED_FR_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define LED_LED_RED_FR_PORT PORTD /*!<@brief PORT device name: PORTD */
#define LED_LED_RED_FR_PIN 2U     /*!<@brief PORTD pin index: 2 */
                                  /* @} */

/*! @name PORTD3 (number 96), LED_BLUE_FR
  @{ */
#define LED_LED_BLUE_FR_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define LED_LED_BLUE_FR_PORT PORTD /*!<@brief PORT device name: PORTD */
#define LED_LED_BLUE_FR_PIN 3U     /*!<@brief PORTD pin index: 3 */
                                   /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void LED(void);

/*! @name PORTB0 (number 53), JS_RIGHT
  @{ */
#define JOYSTICK_JS_RIGHT_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define JOYSTICK_JS_RIGHT_PORT PORTB /*!<@brief PORT device name: PORTB */
#define JOYSTICK_JS_RIGHT_PIN 0U     /*!<@brief PORTB pin index: 0 */
                                     /* @} */

/*! @name PORTB1 (number 54), JS_DOWN
  @{ */
#define JOYSTICK_JS_DOWN_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define JOYSTICK_JS_DOWN_PORT PORTB /*!<@brief PORT device name: PORTB */
#define JOYSTICK_JS_DOWN_PIN 1U     /*!<@brief PORTB pin index: 1 */
                                    /* @} */

/*! @name PORTB2 (number 55), JS_UP
  @{ */
#define JOYSTICK_JS_UP_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define JOYSTICK_JS_UP_PORT PORTB /*!<@brief PORT device name: PORTB */
#define JOYSTICK_JS_UP_PIN 2U     /*!<@brief PORTB pin index: 2 */
                                  /* @} */

/*! @name PORTB3 (number 56), JS_PUSH
  @{ */
#define JOYSTICK_JS_PUSH_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define JOYSTICK_JS_PUSH_PORT PORTB /*!<@brief PORT device name: PORTB */
#define JOYSTICK_JS_PUSH_PIN 3U     /*!<@brief PORTB pin index: 3 */
                                    /* @} */

/*! @name PORTB9 (number 57), JS_LEFT
  @{ */
#define JOYSTICK_JS_LEFT_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define JOYSTICK_JS_LEFT_PORT PORTB /*!<@brief PORT device name: PORTB */
#define JOYSTICK_JS_LEFT_PIN 9U     /*!<@brief PORTB pin index: 9 */
                                    /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void Joystick(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
