/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PORTA15 (number 45), LED_RED_RR
  @{ */
#define BOARD_INITPINS_LED_RED_RR_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_LED_RED_RR_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_LED_RED_RR_PIN 15U    /*!<@brief PORTA pin index: 15 */
                                             /* @} */

/*! @name PORTA17 (number 47), LED_RED_RL
  @{ */
#define BOARD_INITPINS_LED_RED_RL_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_LED_RED_RL_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_LED_RED_RL_PIN 17U    /*!<@brief PORTA pin index: 17 */
                                             /* @} */

/*! @name PORTC8 (number 80), LED_GREEN_FL
  @{ */
#define BOARD_INITPINS_LED_GREEN_FL_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_LED_GREEN_FL_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_LED_GREEN_FL_PIN 8U     /*!<@brief PORTC pin index: 8 */
                                               /* @} */

/*! @name PORTC9 (number 81), LED_RED_FL
  @{ */
#define BOARD_INITPINS_LED_RED_FL_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_LED_RED_FL_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_LED_RED_FL_PIN 9U     /*!<@brief PORTC pin index: 9 */
                                             /* @} */

/*! @name PORTC10 (number 82), LED_BLUE_FL
  @{ */
#define BOARD_INITPINS_LED_BLUE_FL_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_LED_BLUE_FL_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_LED_BLUE_FL_PIN 10U    /*!<@brief PORTC pin index: 10 */
                                              /* @} */

/*! @name PORTC11 (number 83), LED_GREEN_FR
  @{ */
#define BOARD_INITPINS_LED_GREEN_FR_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_LED_GREEN_FR_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_LED_GREEN_FR_PIN 11U    /*!<@brief PORTC pin index: 11 */
                                               /* @} */

/*! @name PORTD2 (number 95), LED_RED_FR
  @{ */
#define BOARD_INITPINS_LED_RED_FR_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_LED_RED_FR_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_LED_RED_FR_PIN 2U     /*!<@brief PORTD pin index: 2 */
                                             /* @} */

/*! @name PORTD3 (number 96), LED_BLUE_FR
  @{ */
#define BOARD_INITPINS_LED_BLUE_FR_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_LED_BLUE_FR_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_LED_BLUE_FR_PIN 3U     /*!<@brief PORTD pin index: 3 */
                                              /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
